### ISSUE TITLE
Ensure Tests Skip on Python Versions Lower than 3.8

### ISSUE THREAD

**Issue by MEHRSHAD-MIRSHEKARY** [ARYAN-NIKNEZHAD/django_logging#47]
Certain tests in the `django_logging` package rely on features only available in Python 3.8 and above. To ensure compatibility across different environments, these tests should be skipped automatically when running on Python versions lower than 3.8. This prevents unnecessary failures in CI/CD pipelines or local environments that might still be using older Python versions.

**Tasks:**
1. Use the `pytest.mark.skipif` to conditionally skip tests on Python versions lower than 3.8.
2. Define a constants file that includes required python version

**Comment by ARYAN-NIKNEZHAD** [comment]
@MEHRSHAD-MIRSHEKARY 
Yeah that's a good idea
